@TaskManager.Api_HostAddress = http://localhost:5081

GET {{TaskManager.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

PATCH {{TaskManager.Api_HostAddress}}/api/manage/task/status?id={{taskId}}
Content-Type: application/json

{
  "status": 2
}

###

DELETE {{TaskManager.Api_HostAddress}}/api/manage/task?id={{taskId}}
Accept: application/json
